### ISSUE TITLE
Almost Copyright

### ISSUE THREAD

**Issue by DroidPlaysM** [QuiverlyRivalry/CastleRaid#10]
Its basically written the same way KingdomCraft Core is that's made by EpicSteve33

**Comment by QuiverlyRivalry** [comment]
with modifications... please be patient with the code :)

**Comment by QuiverlyRivalry** [comment]
I don’t intend to make this KCPE
I just have the core of the old KCPE
I already have work being done for these:
CE
Envoys
UIs
Awesome Stuff :)
I am still thinking should I merge it here, or just make it private
